### ISSUE TITLE
cannot import name 'get_tutorial_dataset' from 'almirah.utils'

### ISSUE THREAD

**Issue by hrani** [girishmm/almirah#1]
After install either via pip or git clone

from almirah.utils import get_tutorial_dataset
cannot import name 'get_tutorial_dataset' from 'almirah.utils'

**Comment by girishmm** [comment]
This is a consequence of splitting utility functions. This is fixed in the dev branch. Till merge and doc generation, please use 

```
from almirah.utils.lib import get_tutorial_dataset
```

**Comment by hrani** [comment]
tests/data/tutorial does not exist for get_tutorial_dataset
